---

-
  name: "Check for presence of OpenShift command line tool"
  register: output
  shell: oc
  args:
    executable: /bin/bash
  failed_when: output.stderr and 'command not found' in output.stderr
  changed_when: False

# We want to be able to log in as a developer, but we might also want to log in as a sys admin (we dont as of yet).
-
  name: "Login as user using the OpenShift command line tool"
  command: 'oc login {{ master_url | default("https://localhost:8443") }} --username={{ oc_user }} --password="{{ oc_password }}" {{ skip_tls | default("false") | bool | ternary("--insecure-skip-tls-verify"," ") }}'
  register: output
-
  debug: var=output
  when: output|failed

-
  name: "Log in to project on update"
  command: "oc project {{ project_name }}"
  when: updating is defined and updating == true
