---

-
  stat:
    path: ~/.bash_profile
  register: bash_file

-
  name: Create user bash file
  file:
    path: ~/.bash_profile
    state: touch
  when: bash_file.stat.exists == False
-
  name: Configure bash profile PATH variable
  lineinfile:
    dest: ~/.bash_profile
    line: "export PATH={{ buildfarm_path_env_var }}"

-
  name: Configure bash profile language encoding
  lineinfile:
    dest: ~/.bash_profile
    line: "export LANG={{ buildfarm_lang_env_var }}"

-
  name: Fix user cache folder permission
  file:
    path: "/Users/{{ macos_user }}/Library/Caches"
    owner: "{{ macos_user }}"
    state: directory
    recurse: yes
  become: true
