---

-
  name: Copy nvm install script
  get_url: 
    url: "{{nvm_install_url}}"
    dest: "{{remote_tmp_dir}}/{{nvm_install_file_name}}"
  environment:
    http_proxy: "{{ proxy_url | default('') }}"
    https_proxy: "{{ proxy_url | default('') }}"

- 
  name: Install nvm
  command: "bash {{remote_tmp_dir}}/{{nvm_install_file_name}}"
  register: install_nvm
  failed_when: install_nvm.rc != 0 and install_nvm.stdout.find('is already installed') == -1
  environment:
    http_proxy: "{{ proxy_url | default('') }}"
    https_proxy: "{{ proxy_url | default('') }}"

-
  name: Install node versions
  shell: "source ~/.bashrc && nvm install {{ item }}"
  with_items: "{{ node_versions }}"
  args:
    executable: /bin/bash
  environment:
    http_proxy: "{{ proxy_url | default('') }}"
    https_proxy: "{{ proxy_url | default('') }}"

- 
  name: Install npm packages
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
  with_items: "{{ npm_packages }}"
  environment:
    http_proxy: "{{ proxy_url | default('') }}"
    https_proxy: "{{ proxy_url | default('') }}"

-
  lineinfile:
    dest: ~/.bash_profile
    line: source "$HOME/.bashrc"