---

-
  name: Check if ruby_domain_name gem is already installed
  shell: "gem list -i '^domain_name$'"
  args:
    executable: /bin/bash
  changed_when: False
  failed_when: ruby_domain_name_installed.stderr and 'command not found' in ruby_domain_name_installed.stderr
  register: ruby_domain_name_installed

-
  name: Copy ruby_domain_name gem to remote host
  copy:
     src: "{{ruby_domain_name_file_path}}"
     dest: "{{remote_tmp_dir}}/{{ruby_domain_name_gem_name}}"
     mode: 0755
  when: ruby_domain_name_installed.rc != 0

-
  name: Install ruby_domain_name gem
  shell: "gem install {{remote_tmp_dir}}/{{ruby_domain_name_gem_name}}"
  args:
    executable: /bin/bash
  become: yes
  when: ruby_domain_name_installed.rc != 0

-
  name: Get list of installed gem packages
  shell: "gem list -i {{item.name}} --version {{item.version}}"
  with_items: "{{ gem_packages }}"
  register: gem_installed
  failed_when: false

-
  name: install gem packages
  shell: "gem install {{ item.item.name }} -v {{ item.item.version }} --minimal-deps"
  with_items: "{{ gem_installed.results }}"
  environment:
    http_proxy: "{{ proxy_url | default('') }}"
    https_proxy: "{{ proxy_url | default('') }}"
  become: yes
  when: item.stdout == "false"
