## ansible roles to be downloaded go in this file
## syntax for importing the role from galaxy
## src: feedhenry.buildfarm

## syntax for importing the role from github


- name: digger-installer
  src: https://github.com/aerogear/digger-installer
  version: master
